### PR TITLE
Added DNS SRV strategy to ConnectionStrategy

### PR DESCRIPTION
**Pull request by cperrin88**

### CODE REVIEW

**Comment by dfish3r** [comment]
I didn't add a static instance of this class because the implementation is not stateless.

**Comment by cperrin88** [comment]
What does that mean in particular?

**Comment by dfish3r** [comment]
The class has mutators which if invoked could break other threads using the same instance.
See DnsSrvConnectionStrategy#setJndiEnvironment
So it's not a good candidate for sharing among various LdapConnections.

**Comment by dfish3r** [comment]
v2 now implements stateful connection strategies.

**Pull request closed without merging**
